// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tienda.Soporte.Infraestructura.Persistence;

namespace Tienda.Soporte.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20201213174225_first")]
    partial class first
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Tienda.Soporte.Domain.Model.Soporte.Appointment", b =>
                {
                    b.Property<Guid>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ServiceOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("appointmentStatus");

                    b.Property<DateTime>("VisitDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("appointmentVisitDate");

                    b.HasKey("AppointmentId")
                        .HasName("appointmentId");

                    b.HasIndex("ServiceOrderId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("Tienda.Soporte.Domain.Model.Soporte.AppointmentHasTechnician", b =>
                {
                    b.Property<Guid>("AppoinmtentHasTechnicianId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AppointmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TechnicianId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AppoinmtentHasTechnicianId")
                        .HasName("appointmentHasTechnicianId");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("TechnicianId");

                    b.ToTable("AppointmentHasTechnicians");
                });

            modelBuilder.Entity("Tienda.Soporte.Domain.Model.Soporte.Client", b =>
                {
                    b.Property<Guid>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("clientAddress");

                    b.HasKey("ClientId")
                        .HasName("clientId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Tienda.Soporte.Domain.Model.Soporte.JobForm", b =>
                {
                    b.Property<Guid>("JobFormId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AppointmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("jobFormDate");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("jobFormDetail");

                    b.HasKey("JobFormId")
                        .HasName("jobFormId");

                    b.HasIndex("AppointmentId");

                    b.ToTable("JobForms");
                });

            modelBuilder.Entity("Tienda.Soporte.Domain.Model.Soporte.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductBrand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("productBrand");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("productName");

                    b.Property<double>("ProductPrice")
                        .HasColumnType("float")
                        .HasColumnName("productPrice");

                    b.HasKey("ProductId")
                        .HasName("productId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Tienda.Soporte.Domain.Model.Soporte.ServiceOrder", b =>
                {
                    b.Property<Guid>("ServiceOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("serviceOrderCreationDate");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("serviceOrderStatus");

                    b.HasKey("ServiceOrderId")
                        .HasName("serviceOrderId");

                    b.HasIndex("ClientId");

                    b.ToTable("ServiceOrders");
                });

            modelBuilder.Entity("Tienda.Soporte.Domain.Model.Soporte.ServiceOrderDetail", b =>
                {
                    b.Property<Guid>("ServiceOrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AlternativeAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("serviceOrderDetailAlternativeAddress");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("serviceOrderDetailDescription");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("serviceOrderDetailPrice");

                    b.Property<Guid?>("ServiceOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ServiceType")
                        .HasColumnType("int")
                        .HasColumnName("serviceOrderDetailType");

                    b.HasKey("ServiceOrderDetailId")
                        .HasName("serviceOrderDetailId");

                    b.HasIndex("ServiceOrderId");

                    b.ToTable("ServiceOrdersDetails");
                });

            modelBuilder.Entity("Tienda.Soporte.Domain.Model.Soporte.ServiceOrderHasProducts", b =>
                {
                    b.Property<Guid>("ServiceOrdersHasProductsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ServiceOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ServiceOrdersHasProductsId")
                        .HasName("serviceOrderHasProductsId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ServiceOrderId");

                    b.ToTable("ServiceOrderHasProducts");
                });

            modelBuilder.Entity("Tienda.Soporte.Domain.Model.Soporte.Technician", b =>
                {
                    b.Property<Guid>("TechnicianId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("technicianCI");

                    b.HasKey("TechnicianId")
                        .HasName("technicianId");

                    b.ToTable("Technicians");
                });

            modelBuilder.Entity("Tienda.Soporte.Domain.Model.Soporte.Appointment", b =>
                {
                    b.HasOne("Tienda.Soporte.Domain.Model.Soporte.ServiceOrder", "ServiceOrder")
                        .WithMany()
                        .HasForeignKey("ServiceOrderId");

                    b.Navigation("ServiceOrder");
                });

            modelBuilder.Entity("Tienda.Soporte.Domain.Model.Soporte.AppointmentHasTechnician", b =>
                {
                    b.HasOne("Tienda.Soporte.Domain.Model.Soporte.Appointment", "Appointment")
                        .WithMany()
                        .HasForeignKey("AppointmentId");

                    b.HasOne("Tienda.Soporte.Domain.Model.Soporte.Technician", "Technician")
                        .WithMany()
                        .HasForeignKey("TechnicianId");

                    b.Navigation("Appointment");

                    b.Navigation("Technician");
                });

            modelBuilder.Entity("Tienda.Soporte.Domain.Model.Soporte.Client", b =>
                {
                    b.OwnsOne("Tienda.SharedKernel.ValueObjects.Email.EmailValue", "Email", b1 =>
                        {
                            b1.Property<Guid>("ClientId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("clientEmail");

                            b1.HasKey("ClientId");

                            b1.ToTable("Clients");

                            b1.WithOwner()
                                .HasForeignKey("ClientId");
                        });

                    b.OwnsOne("Tienda.SharedKernel.ValueObjects.PersonNameValue", "Lastname", b1 =>
                        {
                            b1.Property<Guid>("ClientId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("clientLastname");

                            b1.HasKey("ClientId");

                            b1.ToTable("Clients");

                            b1.WithOwner()
                                .HasForeignKey("ClientId");
                        });

                    b.OwnsOne("Tienda.SharedKernel.ValueObjects.PersonNameValue", "Name", b1 =>
                        {
                            b1.Property<Guid>("ClientId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("clientName");

                            b1.HasKey("ClientId");

                            b1.ToTable("Clients");

                            b1.WithOwner()
                                .HasForeignKey("ClientId");
                        });

                    b.OwnsOne("Tienda.SharedKernel.ValueObjects.PhoneNumber.PhoneNumberValue", "Phone", b1 =>
                        {
                            b1.Property<Guid>("ClientId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("clientPhone");

                            b1.HasKey("ClientId");

                            b1.ToTable("Clients");

                            b1.WithOwner()
                                .HasForeignKey("ClientId");
                        });

                    b.Navigation("Email");

                    b.Navigation("Lastname");

                    b.Navigation("Name");

                    b.Navigation("Phone");
                });

            modelBuilder.Entity("Tienda.Soporte.Domain.Model.Soporte.JobForm", b =>
                {
                    b.HasOne("Tienda.Soporte.Domain.Model.Soporte.Appointment", "Appointment")
                        .WithMany()
                        .HasForeignKey("AppointmentId");

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("Tienda.Soporte.Domain.Model.Soporte.ServiceOrder", b =>
                {
                    b.HasOne("Tienda.Soporte.Domain.Model.Soporte.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Tienda.Soporte.Domain.Model.Soporte.ServiceOrderDetail", b =>
                {
                    b.HasOne("Tienda.Soporte.Domain.Model.Soporte.ServiceOrder", "ServiceOrder")
                        .WithMany()
                        .HasForeignKey("ServiceOrderId");

                    b.Navigation("ServiceOrder");
                });

            modelBuilder.Entity("Tienda.Soporte.Domain.Model.Soporte.ServiceOrderHasProducts", b =>
                {
                    b.HasOne("Tienda.Soporte.Domain.Model.Soporte.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.HasOne("Tienda.Soporte.Domain.Model.Soporte.ServiceOrder", "ServiceOrder")
                        .WithMany()
                        .HasForeignKey("ServiceOrderId");

                    b.Navigation("Product");

                    b.Navigation("ServiceOrder");
                });

            modelBuilder.Entity("Tienda.Soporte.Domain.Model.Soporte.Technician", b =>
                {
                    b.OwnsOne("Tienda.SharedKernel.ValueObjects.Email.EmailValue", "Email", b1 =>
                        {
                            b1.Property<Guid>("TechnicianId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("technicianEmail");

                            b1.HasKey("TechnicianId");

                            b1.ToTable("Technicians");

                            b1.WithOwner()
                                .HasForeignKey("TechnicianId");
                        });

                    b.OwnsOne("Tienda.SharedKernel.ValueObjects.PersonNameValue", "Lastname", b1 =>
                        {
                            b1.Property<Guid>("TechnicianId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("technicianLastname");

                            b1.HasKey("TechnicianId");

                            b1.ToTable("Technicians");

                            b1.WithOwner()
                                .HasForeignKey("TechnicianId");
                        });

                    b.OwnsOne("Tienda.SharedKernel.ValueObjects.PersonNameValue", "Name", b1 =>
                        {
                            b1.Property<Guid>("TechnicianId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("technicianName");

                            b1.HasKey("TechnicianId");

                            b1.ToTable("Technicians");

                            b1.WithOwner()
                                .HasForeignKey("TechnicianId");
                        });

                    b.OwnsOne("Tienda.SharedKernel.ValueObjects.PhoneNumber.PhoneNumberValue", "Phone", b1 =>
                        {
                            b1.Property<Guid>("TechnicianId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("technicianPhone");

                            b1.HasKey("TechnicianId");

                            b1.ToTable("Technicians");

                            b1.WithOwner()
                                .HasForeignKey("TechnicianId");
                        });

                    b.Navigation("Email");

                    b.Navigation("Lastname");

                    b.Navigation("Name");

                    b.Navigation("Phone");
                });
#pragma warning restore 612, 618
        }
    }
}
